### ISSUE TITLE
<a ref="... should be <a href="...

### ISSUE THREAD

**Issue by callym** [Timidger/timidger.github.io#1]
https://github.com/Timidger/timidger.github.io/blob/981d7030f23f656741901fe3297d29bf3b8722c7/designing-a-bi-mutable-directional-tree-safely-in-rust.html#L34

``` html
but not only can that be messy <a ref="...">if we change to...
```

to:

``` html
but not only can that be messy <a href="...">if we change to...
```

**Comment by Timidger** [comment]
Fixed, thanks!
